#!/usr/bin/env python3
"""Run Runtime save-state v0 to v1 migration smoke checks.

This smoke executes `game_runtime` prelaunch save export against a seeded
save-state-v0 profile. It proves the Runtime CLI can read the old save shape,
rewrite it as save-state-v1, and export the migrated profile on this machine.
It does not replace manual platform review, cloud save policy, or release
candidate acceptance.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any


REQUIRED_CHECKS = {
    "runtime_command_migrates_v0",
    "save_file_rewritten_to_v1",
    "export_file_written_as_v1",
    "migration_history_completed",
    "meta_progress_preserved",
    "privacy_and_data_controls_preserved",
    "base_ui_state_initialized",
}


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def load_json_object(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def repo_relative(repo_root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(repo_root.resolve()))
    except ValueError:
        return str(path)


def remove_previous_work_dir(work_dir: Path) -> None:
    marker = work_dir / ".runtime-save-migration-smoke"
    if work_dir.exists():
        if not marker.exists():
            raise RuntimeError(f"refusing to remove unmarked work dir: {work_dir}")
        shutil.rmtree(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)
    marker.write_text("generated by tools/run_runtime_save_migration_smoke.py\n", encoding="utf-8")


def run_command(repo_root: Path, argv: list[str], expected_returncode: int) -> dict[str, Any]:
    result = subprocess.run(
        argv,
        cwd=repo_root,
        check=False,
        text=True,
        capture_output=True,
    )
    return {
        "argv": argv,
        "expected_returncode": expected_returncode,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


def add_check(checks: list[dict[str, Any]], check_id: str, passed: bool, summary: str) -> None:
    checks.append({"id": check_id, "status": "pass" if passed else "fail", "summary": summary})


def seed_v0_save(template: dict[str, Any]) -> dict[str, Any]:
    payload = json.loads(json.dumps(template))
    payload["save_id"] = "runtime-migration-smoke-v0"
    payload["profile_id"] = "migration-smoke-player"
    payload["updated_at"] = "2026-05-29T00:00:00Z"
    meta_progress = payload["meta_progress"]
    meta_progress["resources"]["candy_crystal_shards"] = 42
    meta_progress["resources"]["star_shards"] = 3
    meta_progress["completed_runs"] = 7
    meta_progress["best_survival_seconds"] = 321.5
    meta_progress["unlocks"]["maps"].append("soda-creek")
    meta_progress["unlocks"]["chapters"].append("soda-creek")
    meta_progress["chapters"]["soda-creek"]["unlocked"] = True
    meta_progress["chapters"]["frosting-grassland"]["completed_goals"] = [
        "defeat-runaway-sugar-mixer",
        "survive-10-minutes",
    ]
    return payload


def privacy_defaults_are_off(payload: dict[str, Any]) -> bool:
    settings = payload.get("settings", {})
    return (
        isinstance(settings, dict)
        and settings.get("telemetry_upload_enabled") is False
        and settings.get("raw_replay_upload_enabled") is False
        and settings.get("crash_report_upload_enabled") is False
    )


def data_controls_are_local_only(payload: dict[str, Any]) -> bool:
    controls = payload.get("data_controls", {})
    return (
        isinstance(controls, dict)
        and controls.get("local_only_by_default") is True
        and controls.get("upload_requires_opt_in") is True
        and controls.get("delete_save_available") is True
        and controls.get("export_save_available") is True
        and controls.get("export_format") == "json"
    )


def migration_history_completed(payload: dict[str, Any], source_save_id: str) -> bool:
    history = payload.get("migration_history")
    if not isinstance(history, list) or len(history) != 1 or not isinstance(history[0], dict):
        return False
    entry = history[0]
    return (
        entry.get("migration_id") == "save-state-v0-to-v1"
        and entry.get("source_save_id") == source_save_id
        and entry.get("source_contract_id") == "save-state-v0"
        and entry.get("source_schema_version") == 1
        and entry.get("target_contract_id") == "save-state-v1"
        and entry.get("target_schema_version") == 2
        and entry.get("status") == "completed"
    )


def meta_progress_preserved(source: dict[str, Any], migrated: dict[str, Any]) -> bool:
    source_progress = source.get("meta_progress", {})
    migrated_progress = migrated.get("meta_progress", {})
    return (
        source_progress.get("resources") == migrated_progress.get("resources")
        and source_progress.get("unlocks") == migrated_progress.get("unlocks")
        and source_progress.get("chapters") == migrated_progress.get("chapters")
        and source_progress.get("completed_runs") == migrated_progress.get("completed_runs")
        and source_progress.get("best_survival_seconds")
        == migrated_progress.get("best_survival_seconds")
    )


def base_ui_state_initialized(payload: dict[str, Any]) -> bool:
    state = payload.get("base_ui_state")
    if not isinstance(state, dict):
        return False
    return (
        state.get("selected_panel") == "overview"
        and state.get("last_selected_character_id") == "jar-keeper"
        and state.get("last_selected_map_id") == "frosting-grassland"
        and state.get("last_selected_chapter_id") == "frosting-grassland"
        and isinstance(state.get("codex_view"), dict)
        and isinstance(state.get("privacy_view"), dict)
    )


def finalize_report(report: dict[str, Any]) -> dict[str, Any]:
    errors = list(report.get("errors", []))
    commands = report.get("commands", [])
    if not isinstance(commands, list):
        errors.append("commands must be a list")
        commands = []
    for index, command in enumerate(commands):
        if not isinstance(command, dict):
            errors.append(f"commands[{index}] must be an object")
            continue
        if command.get("returncode") != command.get("expected_returncode"):
            errors.append(
                "command returncode mismatch for "
                f"{' '.join(command.get('argv', []))}: "
                f"expected {command.get('expected_returncode')}, got {command.get('returncode')}"
            )

    checks = report.get("checks", [])
    if not isinstance(checks, list):
        errors.append("checks must be a list")
        checks = []
    check_statuses = {
        str(check.get("id")): check.get("status")
        for check in checks
        if isinstance(check, dict) and isinstance(check.get("id"), str)
    }
    for check_id in sorted(REQUIRED_CHECKS):
        if check_statuses.get(check_id) != "pass":
            errors.append(f"{check_id}: required smoke check did not pass")

    failed_checks = [check_id for check_id, status in check_statuses.items() if status != "pass"]
    report["errors"] = errors
    report["decision"] = (
        "runtime_save_migration_smoke_valid"
        if not errors and not failed_checks
        else "runtime_save_migration_smoke_invalid"
    )
    return report


def build_smoke_report(repo_root: Path, work_dir: Path, template_path: Path) -> dict[str, Any]:
    remove_previous_work_dir(work_dir)
    save_file = work_dir / "profile_v0.json"
    export_file = work_dir / "profile_export_v1.json"
    source_save = seed_v0_save(load_json_object(template_path))
    write_json(save_file, source_save)

    command = run_command(
        repo_root,
        [
            "cargo",
            "run",
            "-p",
            "game_runtime",
            "--",
            "--save-file",
            str(save_file),
            "--export-save",
            str(export_file),
        ],
        0,
    )

    migrated_save = load_json_object(save_file) if save_file.exists() else {}
    exported_save = load_json_object(export_file) if export_file.exists() else {}
    checks: list[dict[str, Any]] = []
    add_check(
        checks,
        "runtime_command_migrates_v0",
        command["returncode"] == 0 and str(export_file) in command["stdout"],
        "Runtime prelaunch export command completed and printed the export path.",
    )
    add_check(
        checks,
        "save_file_rewritten_to_v1",
        migrated_save.get("contract_id") == "save-state-v1" and migrated_save.get("schema_version") == 2,
        "Original save file was rewritten from save-state-v0 to save-state-v1.",
    )
    add_check(
        checks,
        "export_file_written_as_v1",
        exported_save.get("contract_id") == "save-state-v1" and exported_save.get("schema_version") == 2,
        "Exported save file uses save-state-v1.",
    )
    add_check(
        checks,
        "migration_history_completed",
        migration_history_completed(migrated_save, source_save["save_id"])
        and migration_history_completed(exported_save, source_save["save_id"]),
        "Migrated and exported saves record one completed save-state-v0-to-v1 migration entry.",
    )
    add_check(
        checks,
        "meta_progress_preserved",
        meta_progress_preserved(source_save, migrated_save)
        and meta_progress_preserved(source_save, exported_save),
        "Resources, unlocks, chapters, completed runs, and best survival are preserved.",
    )
    add_check(
        checks,
        "privacy_and_data_controls_preserved",
        privacy_defaults_are_off(migrated_save)
        and privacy_defaults_are_off(exported_save)
        and data_controls_are_local_only(migrated_save)
        and data_controls_are_local_only(exported_save),
        "Privacy defaults and local-only data controls remain preserved after migration.",
    )
    add_check(
        checks,
        "base_ui_state_initialized",
        base_ui_state_initialized(migrated_save) and base_ui_state_initialized(exported_save),
        "save-state-v1 base_ui_state is initialized for Runtime meta panel persistence.",
    )

    return finalize_report(
        {
            "report_version": 1,
            "decision": "runtime_save_migration_smoke_pending",
            "repo_root": str(repo_root),
            "work_dir": repo_relative(repo_root, work_dir),
            "template": repo_relative(repo_root, template_path),
            "artifacts": {
                "source_v0_save": repo_relative(repo_root, save_file),
                "exported_v1_save": repo_relative(repo_root, export_file),
            },
            "commands": [command],
            "checks": checks,
            "errors": [],
            "limitations": [
                "This smoke executes Runtime prelaunch CLI actions only; it does not open the Bevy window.",
                "It validates one seeded save-state-v0 migration sample, not every historical save.",
                "It does not replace manual platform path review, cloud save policy, or release candidate approval.",
            ],
        }
    )


def write_markdown(report: dict[str, Any], path: Path) -> None:
    lines = [
        "# Runtime Save Migration Smoke",
        "",
        f"- Decision: `{report['decision']}`",
        f"- Work dir: `{report['work_dir']}`",
        f"- Template: `{report['template']}`",
        "",
        "## Checks",
        "",
        "| Check | Status | Summary |",
        "|---|---|---|",
    ]
    for check in report["checks"]:
        lines.append(f"| `{check['id']}` | `{check['status']}` | {check['summary']} |")

    lines.extend(["", "## Commands", "", "| Command | Return | Expected |", "|---|---:|---:|"])
    for command in report["commands"]:
        rendered = " ".join(command["argv"])
        lines.append(f"| `{rendered}` | {command['returncode']} | {command['expected_returncode']} |")

    lines.extend(["", "## Errors", ""])
    if report["errors"]:
        lines.extend(f"- {error}" for error in report["errors"])
    else:
        lines.append("- None")

    lines.extend(["", "## Limitations", ""])
    lines.extend(f"- {item}" for item in report["limitations"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run Runtime save-state migration smoke.")
    parser.add_argument("--repo-root", type=Path, default=Path("."), help="Repository root")
    parser.add_argument(
        "--template",
        type=Path,
        default=Path("harness/save_contract/save_state_v0_template.json"),
        help="Seed save-state-v0 template",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        required=True,
        help="Generated work directory for temporary save migration artifacts",
    )
    parser.add_argument("--report", type=Path, required=True, help="Write JSON smoke report")
    parser.add_argument("--markdown", type=Path, required=True, help="Write Markdown summary")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    template_path = args.template if args.template.is_absolute() else repo_root / args.template
    report = build_smoke_report(repo_root, args.work_dir, template_path)
    write_json(args.report, report)
    write_markdown(report, args.markdown)
    return 0 if report["decision"] == "runtime_save_migration_smoke_valid" else 1


if __name__ == "__main__":
    raise SystemExit(main())
