#!/usr/bin/env python3
"""Run Runtime local data, privacy, and save-control CLI smoke checks.

This smoke executes `game_runtime` prelaunch actions through `cargo run` and
validates the produced artifacts. It is intentionally narrower than release
privacy acceptance: it proves the local CLI controls work on this machine, not
that legal/privacy/manual gates are passed.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


REQUIRED_CHECKS = {
    "privacy_notice_defaults_local",
    "save_export_created_v1",
    "save_delete_requires_explicit_save_file",
    "save_delete_removes_explicit_file",
    "local_data_export_includes_configured_platform_dirs",
    "local_data_delete_requires_explicit_dirs",
    "local_data_delete_removes_explicit_dirs",
}


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def load_json_object(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def repo_relative(repo_root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(repo_root.resolve()))
    except ValueError:
        return str(path)


def remove_previous_work_dir(work_dir: Path) -> None:
    marker = work_dir / ".runtime-local-data-smoke"
    if work_dir.exists():
        if not marker.exists():
            raise RuntimeError(f"refusing to remove unmarked work dir: {work_dir}")
        shutil.rmtree(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)
    marker.write_text("generated by tools/run_runtime_local_data_smoke.py\n", encoding="utf-8")


def run_command(repo_root: Path, argv: list[str], expected_returncode: int) -> dict[str, Any]:
    result = subprocess.run(
        argv,
        cwd=repo_root,
        check=False,
        text=True,
        capture_output=True,
    )
    return {
        "argv": argv,
        "expected_returncode": expected_returncode,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


def add_check(checks: list[dict[str, Any]], check_id: str, passed: bool, summary: str) -> None:
    checks.append(
        {
            "id": check_id,
            "status": "pass" if passed else "fail",
            "summary": summary,
        }
    )


def seed_local_data(platform_root: Path) -> dict[str, Path]:
    telemetry = platform_root / "telemetry"
    replay = platform_root / "replay"
    crash = platform_root / "crash-reports"
    telemetry.mkdir(parents=True, exist_ok=True)
    replay.mkdir(parents=True, exist_ok=True)
    crash.mkdir(parents=True, exist_ok=True)
    files = {
        "telemetry": telemetry / "session.ndjson",
        "replay": replay / "representative_replay.json",
        "crash_report": crash / "crash_report.json",
    }
    files["telemetry"].write_text('{"event":"runtime_smoke","value":1}\n', encoding="utf-8")
    files["replay"].write_text('{"kind":"runtime_replay_smoke","tick":1}\n', encoding="utf-8")
    files["crash_report"].write_text('{"kind":"runtime_crash_report_smoke"}\n', encoding="utf-8")
    return files


def privacy_defaults_are_off(payload: dict[str, Any]) -> bool:
    settings = payload.get("settings", payload.get("privacy_settings", {}))
    return (
        isinstance(settings, dict)
        and settings.get("telemetry_upload_enabled") is False
        and settings.get("raw_replay_upload_enabled") is False
        and settings.get("crash_report_upload_enabled") is False
    )


def finalize_report(report: dict[str, Any]) -> dict[str, Any]:
    errors = list(report.get("errors", []))
    commands = report.get("commands", [])
    if not isinstance(commands, list):
        errors.append("commands must be a list")
        commands = []
    for index, command in enumerate(commands):
        if not isinstance(command, dict):
            errors.append(f"commands[{index}] must be an object")
            continue
        if command.get("returncode") != command.get("expected_returncode"):
            errors.append(
                "command returncode mismatch for "
                f"{' '.join(command.get('argv', []))}: "
                f"expected {command.get('expected_returncode')}, got {command.get('returncode')}"
            )

    checks = report.get("checks", [])
    if not isinstance(checks, list):
        errors.append("checks must be a list")
        checks = []
    check_statuses = {
        str(check.get("id")): check.get("status")
        for check in checks
        if isinstance(check, dict) and isinstance(check.get("id"), str)
    }
    for check_id in sorted(REQUIRED_CHECKS):
        if check_statuses.get(check_id) != "pass":
            errors.append(f"{check_id}: required smoke check did not pass")

    failed_checks = [check_id for check_id, status in check_statuses.items() if status != "pass"]
    report["errors"] = errors
    report["decision"] = (
        "runtime_local_data_controls_smoke_valid"
        if not errors and not failed_checks
        else "runtime_local_data_controls_smoke_invalid"
    )
    return report


def build_smoke_report(repo_root: Path, work_dir: Path) -> dict[str, Any]:
    remove_previous_work_dir(work_dir)
    platform_root = work_dir / "platform_user_data" / "soft-candy-storm"
    save_export = work_dir / "artifacts" / "profile_export.json"
    local_export = work_dir / "artifacts" / "local_data_export.json"
    seeded_files = seed_local_data(platform_root)
    save_file = platform_root / "saves" / "profile.json"
    telemetry_dir = platform_root / "telemetry"
    replay_dir = platform_root / "replay"
    crash_dir = platform_root / "crash-reports"

    cargo_prefix = ["cargo", "run", "-p", "game_runtime", "--"]
    commands: list[dict[str, Any]] = []
    commands.append(
        run_command(
            repo_root,
            cargo_prefix
            + [
                "--platform-data-root",
                str(platform_root),
                "--print-privacy-notice",
            ],
            0,
        )
    )
    commands.append(
        run_command(
            repo_root,
            cargo_prefix
            + [
                "--platform-data-root",
                str(platform_root),
                "--export-save",
                str(save_export),
            ],
            0,
        )
    )
    save_exists_after_export = save_file.exists()

    commands.append(
        run_command(
            repo_root,
            cargo_prefix
            + [
                "--platform-data-root",
                str(platform_root),
                "--delete-save",
            ],
            2,
        )
    )
    save_exists_after_rejected_delete = save_file.exists()

    commands.append(
        run_command(
            repo_root,
            cargo_prefix
            + [
                "--save-file",
                str(save_file),
                "--delete-save",
            ],
            0,
        )
    )
    save_exists_after_explicit_delete = save_file.exists()

    commands.append(
        run_command(
            repo_root,
            cargo_prefix
            + [
                "--platform-data-root",
                str(platform_root),
                "--export-local-data",
                str(local_export),
            ],
            0,
        )
    )

    commands.append(
        run_command(
            repo_root,
            cargo_prefix
            + [
                "--platform-data-root",
                str(platform_root),
                "--delete-local-data",
            ],
            2,
        )
    )
    local_files_after_rejected_delete = {key: path.exists() for key, path in seeded_files.items()}

    commands.append(
        run_command(
            repo_root,
            cargo_prefix
            + [
                "--local-data-dir",
                str(telemetry_dir),
                "--local-data-dir",
                str(replay_dir),
                "--local-data-dir",
                str(crash_dir),
                "--delete-local-data",
            ],
            0,
        )
    )
    local_files_after_explicit_delete = {key: path.exists() for key, path in seeded_files.items()}

    checks: list[dict[str, Any]] = []
    privacy_stdout = commands[0]["stdout"]
    add_check(
        checks,
        "privacy_notice_defaults_local",
        commands[0]["returncode"] == 0
        and "默认只保存在本机" in privacy_stdout
        and "明确开启" in privacy_stdout
        and "当前 Runtime 没有网络上传传输层" in privacy_stdout
        and privacy_stdout.count("关闭") >= 3,
        "Privacy notice prints local-only defaults, explicit opt-in language, and no upload transport.",
    )

    save_export_payload = load_json_object(save_export) if save_export.exists() else {}
    add_check(
        checks,
        "save_export_created_v1",
        save_exists_after_export
        and save_export.exists()
        and save_export_payload.get("contract_id") == "save-state-v1"
        and save_export_payload.get("schema_version") == 2
        and privacy_defaults_are_off(save_export_payload)
        and save_export_payload.get("data_controls", {}).get("local_only_by_default") is True
        and save_export_payload.get("data_controls", {}).get("upload_requires_opt_in") is True,
        "Save export creates a save-state-v1 profile with local-only default data controls.",
    )

    add_check(
        checks,
        "save_delete_requires_explicit_save_file",
        commands[2]["returncode"] == 2
        and "delete save requires --save-file" in commands[2]["stderr"]
        and save_exists_after_rejected_delete,
        "Save deletion through platform data root is rejected unless --save-file is explicit.",
    )
    add_check(
        checks,
        "save_delete_removes_explicit_file",
        commands[3]["returncode"] == 0 and not save_exists_after_explicit_delete,
        "Explicit --save-file deletion removes only the selected profile file.",
    )

    local_export_payload = load_json_object(local_export) if local_export.exists() else {}
    export_files = local_export_payload.get("files", [])
    exported_relative_paths = {
        str(item.get("relative_path"))
        for item in export_files
        if isinstance(item, dict) and isinstance(item.get("relative_path"), str)
    }
    add_check(
        checks,
        "local_data_export_includes_configured_platform_dirs",
        local_export.exists()
        and local_export_payload.get("kind") == "runtime_local_data_export"
        and privacy_defaults_are_off(local_export_payload)
        and exported_relative_paths
        == {"session.ndjson", "representative_replay.json", "crash_report.json"},
        "Local data export includes telemetry, replay, and crash-report files from the platform data root.",
    )

    add_check(
        checks,
        "local_data_delete_requires_explicit_dirs",
        commands[5]["returncode"] == 2
        and "delete requires at least one explicit --local-data-dir" in commands[5]["stderr"]
        and all(local_files_after_rejected_delete.values()),
        "Local data deletion is rejected when only --platform-data-root provided implicit directories.",
    )
    add_check(
        checks,
        "local_data_delete_removes_explicit_dirs",
        commands[6]["returncode"] == 0
        and all(not exists for exists in local_files_after_explicit_delete.values())
        and telemetry_dir.exists()
        and replay_dir.exists()
        and crash_dir.exists(),
        "Local data deletion clears files under every explicit --local-data-dir while preserving the root dirs.",
    )

    return finalize_report(
        {
            "report_version": 1,
            "decision": "runtime_local_data_controls_smoke_pending",
            "repo_root": str(repo_root),
            "work_dir": repo_relative(repo_root, work_dir),
            "platform_data_root": repo_relative(repo_root, platform_root),
            "artifacts": {
                "save_export": repo_relative(repo_root, save_export),
                "local_data_export": repo_relative(repo_root, local_export),
            },
            "commands": commands,
            "checks": checks,
            "errors": [],
            "limitations": [
                "This smoke executes Runtime prelaunch CLI actions only; it does not open the Bevy window.",
                "It validates local JSON export/delete behavior, not native OS platform data resolution.",
                "It does not replace manual privacy review, manual platform path review, legal review, or release candidate approval.",
                "Upload transport remains intentionally not implemented for this prototype.",
            ],
        }
    )


def write_markdown(report: dict[str, Any], path: Path) -> None:
    lines = [
        "# Runtime Local Data Controls Smoke",
        "",
        f"- Decision: `{report['decision']}`",
        f"- Work dir: `{report['work_dir']}`",
        f"- Platform data root: `{report['platform_data_root']}`",
        "",
        "## Checks",
        "",
        "| Check | Status | Summary |",
        "|---|---|---|",
    ]
    for check in report["checks"]:
        lines.append(f"| `{check['id']}` | `{check['status']}` | {check['summary']} |")

    lines.extend(["", "## Commands", "", "| Command | Return | Expected |", "|---|---:|---:|"])
    for command in report["commands"]:
        rendered = " ".join(command["argv"])
        lines.append(
            f"| `{rendered}` | {command['returncode']} | {command['expected_returncode']} |"
        )

    lines.extend(["", "## Errors", ""])
    if report["errors"]:
        lines.extend(f"- {error}" for error in report["errors"])
    else:
        lines.append("- None")

    lines.extend(["", "## Limitations", ""])
    lines.extend(f"- {item}" for item in report["limitations"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run Runtime local data controls smoke.")
    parser.add_argument("--repo-root", type=Path, default=Path("."), help="Repository root")
    parser.add_argument(
        "--work-dir",
        type=Path,
        required=True,
        help="Generated work directory for temporary Runtime data and export artifacts",
    )
    parser.add_argument("--report", type=Path, required=True, help="Write JSON smoke report")
    parser.add_argument("--markdown", type=Path, required=True, help="Write Markdown summary")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    report = build_smoke_report(repo_root, args.work_dir)
    write_json(args.report, report)
    write_markdown(report, args.markdown)
    return 0 if report["decision"] == "runtime_local_data_controls_smoke_valid" else 1


if __name__ == "__main__":
    raise SystemExit(main())
